name: "Build app"

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    strategy:
      matrix:
        go-version: [ 1.15.x, 1.16.x ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Pulling code
        uses: actions/checkout@v2

      - name: Run build
        run: go build ./...
